// Firmware over BLE (op fw4, lib/ProjectStick/FirmwareTransfer): the mini
// program's vector (fixtures/ble-fw4-vector.json, a copy of Project.StockStick
// miniprogram/tests/fixtures/ble-fw4-vector.json generated by
// scripts/ble-fw4-vector.py) drives the Assembler through an in-memory Io.
#include <gtest/gtest.h>

#include <cstring>
#include <fstream>
#include <iterator>
#include <random>
#include <string>
#include <vector>

#include "BleCrypto.h"
#include "BleSetupProtocol.h"
#include "FirmwareTransfer.h"

using namespace firmware_v4;
using studio_v4::Digest;
using studio_v4::Error;

namespace {
using Bytes = std::vector<uint8_t>;

std::string vectorJson() {
  std::ifstream in(FW4_VECTOR_PATH);
  EXPECT_TRUE(in.good()) << FW4_VECTOR_PATH;
  return std::string(std::istreambuf_iterator<char>(in), std::istreambuf_iterator<char>());
}
// Value of a top-level (or the first nested) `"key": <value>` in the vector.
std::string field(const std::string& json, const std::string& key, size_t from = 0) {
  const size_t at = json.find("\"" + key + "\":", from);
  EXPECT_NE(at, std::string::npos) << key;
  size_t i = json.find_first_not_of(" \n", at + key.size() + 3);
  if (json[i] == '"') return json.substr(i + 1, json.find('"', i + 1) - i - 1);
  return json.substr(i, json.find_first_of(",}\n", i) - i);
}
Bytes unhex(const std::string& hex) {
  Bytes out;
  EXPECT_TRUE(ble_setup::unhex(hex, out));
  return out;
}
Bytes ctrAt(const Bytes& key, const Bytes& nonce, size_t offset, const Bytes& data) {
  uint8_t counter[16];
  memcpy(counter, nonce.data(), 16);
  uint64_t blocks = offset / 16;
  for (int i = 15; i >= 0 && blocks; --i) {
    const uint64_t sum = counter[i] + (blocks & 255);
    counter[i] = sum & 255;
    blocks = (blocks >> 8) + (sum >> 8);
  }
  const size_t skip = offset % 16;
  Bytes in(skip + data.size(), 0), out(in.size());
  memcpy(in.data() + skip, data.data(), data.size());
  EXPECT_TRUE(ble_crypto::aes256Ctr(key.data(), counter, in.data(), out.data(), in.size()));
  return Bytes(out.begin() + skip, out.end());
}

class MemoryIo : public Io {
 public:
  Bytes out, stage;
  size_t readAt = 0;
  std::vector<std::pair<size_t, size_t>> checkpoints;
  bool write(const uint8_t* data, size_t size) override {
    out.insert(out.end(), data, data + size);
    return true;
  }
  bool stageBegin() override {
    stage.clear();
    return true;
  }
  bool stageWrite(const uint8_t* data, size_t size) override {
    stage.insert(stage.end(), data, data + size);
    return true;
  }
  bool stageRewind() override {
    readAt = 0;
    return true;
  }
  int stageRead(uint8_t* data, size_t size) override {
    const size_t count = std::min(size, stage.size() - readAt);
    memcpy(data, stage.data() + readAt, count);
    readAt += count;
    return static_cast<int>(count);
  }
  bool checkpoint(size_t rawDone, size_t streamOffset) override {
    checkpoints.emplace_back(rawDone, streamOffset);
    return true;
  }
};

struct Vector {
  std::string json = vectorJson();
  Bytes key = unhex(field(json, "K")), nonce = unhex(field(json, "N"));
  Bytes firmware = unhex(field(json, "firmware_hex"));
  Bytes plain = unhex(field(json, "plain_hex"));
  Bytes encrypted = unhex(field(json, "encrypted_hex"));
  size_t size = std::stoul(field(json, "size"));
  std::string sha = field(json, "sha256");
  size_t resumeOffset = std::stoul(field(json, "received", json.find("\"resume\"")));
  Bytes resumeEncrypted = unhex(field(json, "encrypted_hex", json.find("\"resume\"")));
  Digest digest() const {
    Digest d{};
    EXPECT_TRUE(studio_v4::parseDigest(sha.c_str(), d));
    return d;
  }
  Bytes streamKey() const {
    uint8_t k[32];
    const std::string message = "enc|" + field(json, "N");
    EXPECT_TRUE(ble_crypto::hmacSha256(key.data(), key.size(), reinterpret_cast<const uint8_t*>(message.data()),
                                       message.size(), k));
    return Bytes(k, k + 32);
  }
};

void feedInChunks(Assembler& a, const Bytes& data, unsigned seed) {
  std::mt19937 rng(seed);
  for (size_t at = 0; at < data.size();) {
    const size_t take = std::min<size_t>(data.size() - at, 1 + rng() % 504);
    ASSERT_TRUE(a.feed(data.data() + at, take)) << studio_v4::errorName(a.error());
    at += take;
  }
}
}  // namespace

TEST(FirmwareTransfer, ProofMatchesVector) {
  Vector v;
  const std::string message = beginMessage(field(v.json, "device_id"), field(v.json, "N"),
                                           std::stoul(field(v.json, "epoch")), field(v.json, "version"), v.sha,
                                           v.size, std::stoll(field(v.json, "time")));
  EXPECT_EQ(message, field(v.json, "proof_message"));
  EXPECT_EQ(ble_setup::mac(field(v.json, "K"), message), field(v.json, "proof"));
  EXPECT_EQ(ble_setup::hex(v.streamKey().data(), 32), field(v.json, "stream_key"));
}

TEST(FirmwareTransfer, CipherMatchesVector) {
  Vector v;
  EXPECT_EQ(ctrAt(v.streamKey(), v.nonce, 0, v.plain), v.encrypted);
  const Bytes tail(v.plain.begin() + v.resumeOffset, v.plain.end());
  EXPECT_EQ(ctrAt(v.streamKey(), v.nonce, v.resumeOffset, tail), v.resumeEncrypted);
}

TEST(FirmwareTransfer, FullStreamRebuildsTheImage) {
  Vector v;
  const Bytes plain = ctrAt(v.streamKey(), v.nonce, 0, v.encrypted);
  for (unsigned seed : {1u, 2u, 3u}) {
    MemoryIo io;
    Assembler a;
    ASSERT_TRUE(a.begin(io, v.size, v.digest(), 0, 0));
    feedInChunks(a, plain, seed);
    EXPECT_EQ(a.phase(), Assembler::Phase::Complete);
    EXPECT_EQ(io.out, v.firmware);
    // One checkpoint per block, at the vector's record boundaries.
    ASSERT_EQ(io.checkpoints.size(), 3u);
    EXPECT_EQ(io.checkpoints[0], std::make_pair(size_t(32768), size_t(11010)));
    EXPECT_EQ(io.checkpoints[1], std::make_pair(size_t(65536), size_t(25013)));
    EXPECT_EQ(io.checkpoints[2], std::make_pair(size_t(70000), size_t(27240)));
  }
}

TEST(FirmwareTransfer, ResumeAtTheSecondBlockBoundary) {
  Vector v;
  MemoryIo io;
  io.out.assign(v.firmware.begin(), v.firmware.begin() + 65536);
  Assembler a;
  ASSERT_TRUE(a.begin(io, v.size, v.digest(), 65536, v.resumeOffset));
  a.hashPrefix(io.out.data(), io.out.size());
  feedInChunks(a, ctrAt(v.streamKey(), v.nonce, v.resumeOffset, v.resumeEncrypted), 7);
  EXPECT_EQ(a.phase(), Assembler::Phase::Complete);
  EXPECT_EQ(io.out, v.firmware);
  EXPECT_EQ(a.streamOffset(), v.plain.size());
}

TEST(FirmwareTransfer, RejectsBadStreams) {
  Vector v;
  {  // a wrong announced hash
    MemoryIo io;
    Assembler a;
    Digest wrong = v.digest();
    wrong[0] ^= 1;
    ASSERT_TRUE(a.begin(io, v.size, wrong, 0, 0));
    EXPECT_FALSE(a.feed(v.plain.data(), v.plain.size()));
    EXPECT_EQ(a.error(), Error::ChecksumMismatch);
  }
  {  // a record for the wrong offset
    MemoryIo io;
    Assembler a;
    ASSERT_TRUE(a.begin(io, v.size, v.digest(), 0, 0));
    Bytes bad = v.plain;
    bad[1] = 0x10;  // raw_offset 4096
    EXPECT_FALSE(a.feed(bad.data(), bad.size()));
    EXPECT_EQ(a.error(), Error::FrameMismatch);
  }
  {  // corrupt deflate data
    MemoryIo io;
    Assembler a;
    ASSERT_TRUE(a.begin(io, v.size, v.digest(), 0, 0));
    Bytes bad = v.plain;
    for (size_t i = 8; i < 40; ++i) bad[i] ^= 0x5a;
    EXPECT_FALSE(a.feed(bad.data(), bad.size()));
  }
  {  // invalid geometry
    MemoryIo io;
    Assembler a;
    EXPECT_FALSE(a.begin(io, 0, v.digest(), 0, 0));
    EXPECT_FALSE(a.begin(io, MAX_IMAGE_BYTES + 1, v.digest(), 0, 0));
    EXPECT_FALSE(a.begin(io, v.size, v.digest(), 1000, 10));
    EXPECT_FALSE(a.begin(io, v.size, v.digest(), 32768, 0));
  }
}
