#!/usr/bin/env python3
"""Turns the mini program's BLE transfer protocol 4 vectors
(Project.StockStick miniprogram/tests/fixtures/ble-v4-vectors.json) into
BleV4Vectors.h for the firmware host test. Both sides must pass the same file.

  python3 test/project_stick_core/gen_ble_v4_vectors.py <ble-v4-vectors.json>
"""
import json, os, sys

v = json.load(open(sys.argv[1]))
out = []
w = out.append
def s(x): return json.dumps(x)
w('// Generated by gen_ble_v4_vectors.py from the mini program vectors; do not edit.')
w('#pragma once')
w('#include <cstddef>')
w('#include <cstdint>')
w('namespace ble_v4_vectors {')
for k in ('K', 'N', 'stream_key', 'device_id', 'task'):
    w(f'constexpr const char* {k.upper()} = {s(v[k])};')
w(f'constexpr uint32_t EPOCH = {v["epoch"]};')
w(f'constexpr int64_t TIME = {v["time"]};')
p = v['program']
w(f'constexpr size_t PROGRAM_SIZE = {p["size"]};')
w(f'constexpr size_t PROGRAM_HEADER = {p["header"]};')
w(f'constexpr const char* PROGRAM_SHA256 = {s(p["sha256"])};')
w(f'constexpr const char* PROGRAM_HEADER_HEX = {s(p["header_hex"])};')
w('struct Frame { const char* digest; const char* deflate; };')
w('constexpr Frame FRAMES[] = {')
for f in p['frames']: w(f'  {{{s(f["digest"])}, {s(f["deflate"])}}},')
w('};')
w(f'constexpr const char* SINGLE_SHA256 = {s(v["single"]["sha256"])};')
w('struct Resume { size_t received; const char* need; const char* encrypted; };')
w('struct Case { const char* name; bool single; int have[4]; size_t haveCount; const char* need; size_t needCount;')
w('              const char* message; const char* hash; size_t size; size_t header; int64_t expires; const char* proof;')
w('              const char* plain; const char* encrypted; Resume resumes[4]; size_t resumeCount; };')
w('constexpr Case CASES[] = {')
for c in v['cases']:
    op = c['begin4']['op']
    have = (c['have'] + [0, 0, 0, 0])[:4]
    res = c['resumes'] + [{'received': 0, 'need': '', 'encrypted': ''}] * (4 - len(c['resumes']))
    w(f'  {{{s(c["name"])}, {"true" if op["header"] == 0 else "false"}, {{{", ".join(map(str, have))}}}, {len(c["have"])}, '
      f'{s(c["need"])}, {c["need_count"]}, {s(c["begin4"]["message"])}, {s(op["hash"])}, {op["size"]}, {op["header"]}, '
      f'{op["expires"]}, {s(op["proof"])}, {s(c["plain"])}, {s(c["encrypted"])}, {{')
    for r in res[:4]: w(f'    {{{r["received"]}, {s(r["need"])}, {s(r["encrypted"])}}},')
    w(f'  }}, {len(c["resumes"])}}},')
w('};')
w('struct Progress { uint32_t received; uint8_t state, error; uint16_t needCount; uint32_t seq; const char* hex; };')
w('constexpr Progress PROGRESS[] = {')
for g in v['progress']:
    w(f'  {{{g["received"]}u, {g["state"]}, {g["error"]}, {g["needCount"]}, {g["seq"] % (1 << 32)}u, {s(g["hex"])}}},')
w('};')
w('}  // namespace ble_v4_vectors')
open(os.path.join(os.path.dirname(os.path.abspath(__file__)), 'BleV4Vectors.h'), 'w').write('\n'.join(out) + '\n')
