// The contents of this file are generated by ./lib/EpdFont/scripts/build-font-ids.sh
#pragma once

#define UI_10_FONT_ID (-1656731271)
#define UI_12_FONT_ID (1810504333)
#define SMALL_FONT_ID (2082034080)
#define NOTOSANSSC_10_FONT_ID (-1169223036)
#define NOTOSANSSC_12_FONT_ID (105960020)
#define NOTOSANSSC_13_FONT_ID (165072000)

// Font ID 0 is reserved as the "not found" sentinel.
// Guard against any hash accidentally producing 0.
static_assert(UI_10_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(UI_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(SMALL_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANSSC_10_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANSSC_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANSSC_13_FONT_ID != 0, "Font ID collision with sentinel");
